MAGE/urls.py
# coding: utf-8
'''
    @license: Apache License, Version 2.0
    @copyright: 2007-2022 Marc-Antoine Gouillart
    @author: Marc-Antoine Gouillart
'''

from django.urls import include, path, re_path
from django.contrib.admin import autodiscover
from django.contrib.auth import views as auth_views
from ref.admin import site
from django.conf import settings
autodiscover()
from ref.views.misc import welcome
from ref import views as ref_views

urlpatterns = [
    # core applications
    re_path(r'^ref/', include('ref.urls')),
    re_path(r'^scm/', include('scm.urls')),

    # Login & co
    re_path(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    re_path(r'^accounts/scriptlogin/(?P<username>.*)/(?P<password>.*)$', ref_views.misc.script_login, name='script_login'),
    re_path(r'^accounts/scriptlogin$', ref_views.misc.script_login_post, name='script_login_post'),
    re_path(r'^accounts/forcelogging$', ref_views.misc.force_login, name='force_login'),
    re_path(r'^accounts/scriptlogout$', ref_views.misc.script_logout, name='script_logout'),
    re_path(r'^accounts/logout/$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    re_path(r'^.*/logout/$', auth_views.LogoutView.as_view(next_page='/')),  # including admin logout
    
    # Admin & admin doc
    re_path(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    re_path(r'^admin/', site.urls),
    
    # Welcome screen (slash mapping)
    re_path(r'^$', welcome, name='welcome'),
]

if settings.DEBUG:
    try:
        import debug_toolbar
        urlpatterns += [ path('__debug__/', include(debug_toolbar.urls)), ]
    except:
        pass

ref/urls.py
# coding: utf-8
'''
    @license: Apache License, Version 2.0
    @copyright: 2007-2022 Marc-Antoine Gouillart
    @author: Marc-Antoine Gouillart
'''

from django.urls import include, path, re_path
from ref import views

app_name='ref'

urlpatterns_project = [
    ###########################################################################
    ## Interactive views
    ###########################################################################

    # Welcome pages
    re_path(r'^$', views.misc.project, name='project'),

    # Environment referential consultation
    re_path(r'^envt/shared/$', views.shared_ci, name='shared_ci'),
    re_path(r'^envt/(?P<envt_id>\d+)$', views.envt, name='envt'),
    re_path(r'^envt/(?P<envt_name>.*)/duplicate$', views.envt_duplicate_name, name='envt_duplicate'),

    # Meta descriptions consultation (modification is inside admin)
    re_path(r'type/$', views.model_types, name='types'),
    re_path(r'types_details/$', views.model_detail, name='types_details'),

    ## CI creation and edit forms
    re_path(r'ci/new/$', views.new_items, name='new_item'),
    re_path(r'ci/new/(?P<description_id>\d*)$', views.new_ci_step1, name='new_item_ci'),
    re_path(r'ci/(?P<instance_id>\d*)$', views.new_ci_step2, name='edit_ci'),
    re_path(r'^instance/envt/(?P<envt_id>\d+)$', views.envt_instances, name='instance_envt'),

    ## Graphs
    re_path(r'gph/full/$', views.carto_full, name='grfull'),
    re_path(r'gph/marsupilamographe/$', views.carto_form, name='cartoform'),
    re_path(r'gph/mplgdata/$', views.carto_content_form, name='cartoformdata'),
    re_path(r'gph/mplgdatafull/(?P<collapse_threshold>\d+)/$', views.carto_content_full, name='cartofulldata'),
    re_path(r'gph/mplgdatasimple/(?P<ci_id_list>[\d,]*)/(?P<collapse_threshold>\d+)/(?P<select_related>\d+)$', views.carto_content, name='cartosimpledata'),
    re_path(r'gph/mplgdatadebug$', views.carto_debug, name='cartodebugdata'),
    re_path(r'gph/structuredata/$', views.carto_description_content, name='cartostructuredata'),
    re_path(r'gph/structure/$', views.carto_description, name='cartostructure'),

    ## Misc
    re_path(r'ci/backuped/$', views.backuped, name='backuped'),

    ## Referential debug/migration
    re_path(r'^debug$', views.debug, name='debug'),
    re_path(r'^instance/debug/all$', views.edit_all_comps_meta, name='instance_all'),
    re_path(r'^instance/debug/descr/(?P<descr_id>\d+)$', views.descr_instances_reinit, name='instance_descr_reinit'),
    re_path(r'^control$', views.control, name='control'),
]

urlpatterns_nonproject = [
    ## Misc (pages)
    re_path(r'urls/$', views.urls, name='urls'),
    re_path(r'clearcache', views.clear_cache, name='clear_cache'),

    ## Script helpers (bash script download)
    re_path(r'^helpers/lib/bash$', views.shelllib_bash, name='helper_bash'),


    ###########################################################################
    ## Script APIs
    ###########################################################################

    ## MQL (scripting API)
    re_path(r'mqltester/$', views.mql_tester, name='mqltester'),
    re_path(r'mql/(?P<output_format>.*)/(?P<query>.*)$', views.mql_query, name='mqlquery'),
]

urlpatterns = [
    re_path(r'^project/(?P<project_id>[\w\-_]+)/', include(urlpatterns_project)),
    path('', include(urlpatterns_nonproject)),
]

scm/urls.py
# coding: utf-8
'''
    @license: Apache License, Version 2.0
    @copyright: 2007-2022 Marc-Antoine Gouillart
    @author: Marc-Antoine Gouillart
'''

from django.urls import re_path, include
from django.conf import settings

from scm import views

app_name='scm'

# Interactive views & forms
urlpatterns_interactive = [
    ###########################################################################
    ## Interactive views
    ###########################################################################

    # Progression
    re_path(r'envt/(?P<envt_name>.+)/hist/(?P<limit>\d+)/', views.all_installs, name='envtinstallhistprm'),
    re_path(r'envt/(?P<envt_name>.+)/hist/', views.all_installs, {'limit': 90}, name='envtinstallhist'),

    # Delivery referential
    re_path(r'delivery/$', views.delivery_list, name='deliveries'),
    re_path(r'delivery/(?P<iset_id>\d+)$', views.delivery, name='delivery_detail'),

    # Delivery hand-off forms
    re_path(r'delivery/edit/$', views.delivery_edit, name='delivery_create'),
    re_path(r'delivery/(?P<iset_id>\d*)/edit/$', views.delivery_edit, name='delivery_edit'),
    re_path(r'delivery/(?P<iset_id>\d*)/editdep/$', views.delivery_edit_dep, name='delivery_edit_dep'),

    # Applying installable sets/items - forms
    re_path(r'is/(?P<iset_id>\d*)/testonenvtform/(?P<envt_id_or_name>.+)$', views.iset_test, name='delivery_prereqs_test'),
    re_path(r'is/(?P<iset_id>\d*)/applytoenvt/(?P<envt_id_or_name>.+)/force$', views.iset_apply_envt, {'force_prereqs' : True}, name='iset_apply_envt_force'),
    re_path(r'is/(?P<iset_id>\d*)/applytoenvt/(?P<envt_id_or_name>.+)$', views.iset_apply_envt, {'force_prereqs' : False}, name='iset_apply_envt_force'),
    re_path(r'bck/$', views.backup_list, name='backup_list'),
    re_path(r'bck/archive$', views.backup_list, {'archive': True}, name='backup_list_archive'),
    re_path(r'bck/(?P<bck_id>\d*)$', views.backup_detail, name='backup_detail'),
    
    # Backup
    re_path(r'bck/create/envtdefault/(?P<envt_name>.*)$', views.backup_envt, name='backup_envt'),
    re_path(r'bck/create/form/(?P<envt_name>.*)$', views.backup_envt_manual, name='backup_envt_manual'),
    re_path(r'bck/latest/ci/(?P<ci_id>\d*)/age$', views.latest_ci_backupset_age_mn, name='latest_ci_backupset_age_mn'),
    re_path(r'bck/latest/ci/(?P<ci_id>\d*)/id$', views.latest_ci_backupset_id, name='latest_ci_backupset_id'),

    # Retrieving current version of elements
    re_path(r'version/summary/$', views.lc_versions_per_environment, name='lc_installs_envts'),
    re_path(r'version/lc/$', views.lc_list, name='lc_list'),
    re_path(r'version/lc/(?P<lc_id>\d*)$', views.lc_versions, name='lc_versions'),

    # Tags
    re_path(r'tag/$', views.tag_list, name='tag_list'),
    re_path(r'tag/(?P<tag_id>\d*)$', views.tag_detail, name='tag_detail'),
    re_path(r'tag/create/(?P<envt_name>.*)/(?P<tag_name>.*)$', views.tag_create, name='tag_create'),
    re_path(r'tag/(?P<tag_id>.*)/remove$', views.tag_remove, name='tag_remove'),

    # IS life cycle
    re_path(r'is/(?P<iset_id>\d*)/validate$', views.iset_validate, name='iset_validate'),
    re_path(r'is/(?P<iset_id>\d*)/invalidate$', views.iset_invalidate, name='iset_invalidate'),
    re_path(r'is/(?P<is_id>\d*)/archive$', views.iset_archive, name='iset_archive'),
    re_path(r'is/(?P<is_id>\d*)/unarchive$', views.iset_unarchive, name='iset_unarchive'),
]

urlpatterns_script = [

    ###########################################################################
    ## Script APIs (using direct path without project for ascending compatibility)
    ###########################################################################

    # Applying installable sets/items
    re_path(r'is/(?P<iset_id>\d*)/testonenvtscript/(?P<envt_id_or_name>.+)$', views.iset_test_script, name='delivery_prereqs_test_script'),
    re_path(r'is/(?P<iset_id>\d*)/applytoenvt/(?P<envt_id_or_name>.+)$', views.iset_apply_envt, name='iset_apply_envt'),
    re_path(r'ii/(?P<ii_id>\d+)/apply/(?P<envt_name>.+)/(?P<instance_id>\d+)$', views.delivery_ii_apply_envt, name='delivery_apply_ii_single'),
    re_path(r'ii/(?P<ii_id>\d+)/testonenvtscriptfull/(?P<envt_name>.+)$', views.delivery_ii_test_envt, {'full_delivery': True}, name='delivery_test_ii_set'),
    re_path(r'ii/(?P<ii_id>\d+)/testonenvtscriptsingle/(?P<envt_name>.+)$', views.delivery_ii_test_envt, name='delivery_test_ii_single'),
    re_path(r'ii/(?P<ii_id>\d+)/installmethod/(?P<ci_id>\d+)$', views.ii_test_applicable_to_ci, name='ii_test_compat_ci'),

    # Retrieving current version of elements
    re_path(r'version/lc/(?P<lc_id>\d*)/json$', views.get_lc_versions, name='lc_versions_export'),
    
    # Tags
    re_path(r'tag/create/(?P<envt_name>.*)/(?P<tag_name>.*)$', views.tag_create_script, name='tag_script_create'),
    re_path(r'tag/(?P<tag_id>.*)/remove$', views.tag_remove_script, name='tag_script_remove'),
    
    # Backup
    re_path(r'bck/create/envtdefault/(?P<envt_name>.*)$', views.backup_envt, name='backup_script_envt'),
    re_path(r'bck/create/script/(?P<envt_name>.*)/(?P<ci_id>\d*)$', views.backup_script, name='backup_script_create'),
    re_path(r'bck/create/script/(?P<envt_name>.*)/(?P<ci_id>\d*)/(?P<bck_id>\d*)$', views.backup_script, name='backup_script_add'),
    re_path(r'bck/latest/envt/(?P<envt_name>.*)/id$', views.latest_envt_backupset_id, name='latest_envt_backupset_id'),

    # Queries on IS & II
    re_path(r'is/(?P<iset>.*)/export/(?P<output_format>.*)$', views.iset_export, name='iset_export'),
    re_path(r'is/(?P<iset_name>.*)/id$', views.iset_id, name='iset_id'),
    re_path(r'is/(?P<iset_id>.+)/ii/iicompatlist/(?P<ci_id>\d+)$', views.iset_get_applicable_ii, name='iset_ii_ii_compat'),
    re_path(r'ii/(?P<ii_id>\d+)/export/sh$', views.ii_export, name='ii_export'),

    # IS life cycle
    re_path(r'is/(?P<iset_id>\d*)/validate$', views.iset_validate_script, name='iset_script_validate'),
    re_path(r'is/(?P<iset_id>\d*)/invalidate$', views.iset_invalidate_script, name='iset_script_invalidate'),
    re_path(r'is/(?P<is_id>\d*)/archive$', views.iset_archive_script, name='iset_script_archive'),
    re_path(r'is/(?P<is_id>\d*)/unarchive$', views.iset_unarchive_script, name='iset_script_unarchive'),
]

urlpatterns = [
    re_path(r'^project/(?P<project_id>[\w\-_]+)/', include(urlpatterns_script)),
    re_path(r'^', include((urlpatterns_script, 'scm'), namespace='default_project'), kwargs={'project_id': settings.DEFAULT_PROJECT_ID}),
    re_path(r'^project/(?P<project_id>[\w\-_]+)/', include(urlpatterns_interactive)),
]

ref/views/acl.py
# coding: utf-8
import json
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.contrib.auth.views import redirect_to_login
from django.db.transaction import atomic
from django.shortcuts import render_to_response, redirect
from ref.models.ou import PERMISSIONS, AclAuthorization, folder_permission_required
from ref.models.classifier import AdministrationUnit


@atomic
@folder_permission_required('change_permissions')
def set_acl(request, folder_id):
    folder = AdministrationUnit.objects.get(pk=folder_id)
    groups = Group.objects.order_by('name').all()

    if request.method == 'GET':
        acl = {}
        for ace in folder.acl.all():
            if acl.has_key(ace.group.name):
                acl[ace.group.name].append(ace.codename)
            else:
                acl[ace.group.name] = [ace.codename, ]

        groupsdic = {}
        for group in groups:
            groupsdic[group.id] = group.name

        return render_to_response('ref/acl_edit.html',
                                  {'folder': folder, 'groups': json.dumps(groupsdic), 'acl': json.dumps(acl),
                                   'perms': json.dumps(PERMISSIONS)})

    if request.method == 'POST':
        d = json.loads(request.body)
        for ace in folder.acl.all():
            ace.delete()

        for group_name, perm_list in d.items():
            if group_name == '_block' or len(perm_list) == 0:
                continue
            group = [g for g in groups if g.name == group_name][0]

            for perm in perm_list:
                AclAuthorization(target=folder, codename=perm, group=group).save()

        folder.block_inheritance = bool(d['_block'])

        return redirect("ref:set_acl", folder_id)


@atomic
@login_required
def remove_folder(request, folder_id):
    folder = AdministrationUnit.objects.get(pk=folder_id)
    parent_id = folder.parent_id

    if not request.user.has_perm('delete_folder', parent_id):
        return redirect_to_login(request.path)

    folder.delete()
    return redirect('ref:project_home', parent_id)

ref/views/display.py
# coding: utf-8

from django.shortcuts import render
from django.db.models.query import Prefetch
from django.db.models import Q
from django.db.models.aggregates import Count

from ref.models.instances import Environment, ComponentInstance, \
    ComponentInstanceField
from ref.models.description import ImplementationFieldDescription, \
    ImplementationComputedFieldDescription


def envt(request, envt_id):
    envt = Environment.objects.\
                    select_related('typology').\
                    get(pk=envt_id)
    
    deleted = []
    if request.user.is_authenticated and request.user.has_perm(request.project.perm_change):
        deleted = ComponentInstance.objects.filter(environments__id=envt_id, deleted=True).\
                    select_related('description').\
                    order_by('description__name', 'id')
    
    sec = (False,)
    if not envt.protected or (request.user.is_authenticated and request.user.has_perm(request.project.perm_see_allfields)):
        sec = (True, False)
        
    cis = ComponentInstance.objects.filter(environments__id=envt_id, deleted=False).\
                    select_related('description').\
                    select_related('instanciates__implements__application').\
                    prefetch_related(Prefetch('field_set', queryset=ComponentInstanceField.objects.filter(field__widget_row__gte=0, field__sensitive__in=sec).order_by('field__widget_row', 'field__id'))).\
                    prefetch_related(Prefetch('description__field_set', queryset=ImplementationFieldDescription.objects.filter(widget_row__gte=0, sensitive__in=sec).order_by('widget_row', 'id'))).\
                    prefetch_related(Prefetch('description__computed_field_set', queryset=ImplementationComputedFieldDescription.objects.filter(widget_row__gte=0, sensitive__in=sec).order_by('widget_row', 'id'))).\
                    order_by('description__tag', 'description__name')

    return render(request, 'ref/envt.html', {'envt': envt, 'deleted': deleted, 'cis' : cis})

def backuped(request):
    cis = ComponentInstance.objects.filter(include_in_envt_backup=True, deleted=False).\
            select_related('instanciates__implements__application').\
            select_related('description').\
            prefetch_related(Prefetch('environments', queryset=Environment.objects.filter(project=request.project)))
    return render(request, 'ref/instance_backup.html', {'cis': cis})


def shared_ci(request):
    deleted = []
    if request.user.is_authenticated and request.user.has_perm(request.project.perm_change):
        deleted = ComponentInstance.objects.annotate(num_envt=Count('environments')).filter(~Q(num_envt=1), deleted=True, project=request.project).\
                    select_related('description').\
                    order_by('description__name', 'id')
    
    sec = (False,)
    if request.user.is_authenticated and request.user.has_perm(request.project.perm_see_allfields):
        sec = (True, False)
        
    cis = ComponentInstance.objects.annotate(num_envt=Count('environments')).filter(~Q(num_envt=1), deleted=False, project=request.project).\
                    select_related('description').\
                    prefetch_related('environments').\
                    prefetch_related(Prefetch('field_set', queryset=ComponentInstanceField.objects.filter(field__widget_row__gte=0, field__sensitive__in=sec).order_by('field__widget_row', 'field__id'))).\
                    prefetch_related(Prefetch('description__field_set', queryset=ImplementationFieldDescription.objects.filter(widget_row__gte=0, sensitive__in=sec).order_by('widget_row', 'id'))).\
                    prefetch_related(Prefetch('description__computed_field_set', queryset=ImplementationComputedFieldDescription.objects.filter(widget_row__gte=0, sensitive__in=sec).order_by('widget_row', 'id'))).\
                    order_by('description__tag', 'description__name')

    return render(request, 'ref/envt_shared.html', {'deleted': deleted, 'cis' : cis})

ref/templates/ref/control.html
{% extends "base.html" %}
{% block pagetitle %}debug{% endblock %}
{% block maintitle %}Contrôles du référentiel{% endblock %}


{% block content %}
<div class='t3 metFormSection'>Manques de valeurs (à corriger obligatoirement)</div>
<table class='table table-condensed table-bordered table-hover'>
    <tr><th></th><th>ID</th><th>Type</th><th>Environnements</th><th>Champ manquant ou vide</th></tr>
	{% for ci, errors in missing_field.items %}  
	   {% for error in errors %}
	       <tr>
	           <td><a href="{% url 'ref:edit_ci' ci.id %}" target="_blank">Corriger</a></td>
               <td>{{ ci.id }}</td>
               <td><a href="{% url 'ref:instance_descr_reinit' ci.description_id %}" target="_blank">{{ci.description.name}}</a></td>
               <td>{{ci.environments_str}}</td>
               <td>{{error.name}}</td>
           </tr>
        {% endfor %}
    {% endfor %}
</table>

<div class='t3 metFormSection'>Manques de relations (à corriger obligatoirement)</div>
<table class='table table-condensed table-bordered table-hover'>
    <tr><th>ID</th><th>Type</th><th>Environnements</th><th>Relation manquante ou incomplète</th></tr>
    {% for ci, errors in missing_rel.items %}  
        {% for error in errors %}
           <tr>
	           <td>{{ ci.id }}</td>
               <td><a href="{% url 'ref:instance_descr_reinit' ci.description_id %}" target="_blank">{{ci.description.name}}</a></td>
               <td>{{ci.environments_str}}</td>
               <td>{{error.name}}</td>
           </tr>
        {% endfor %}
    {% endfor %}
</table>

<div class='t3 metFormSection'>Multiples environnements (potentiellement normal)</div>
<table class='table table-condensed table-bordered table-hover'>
    <tr><th>ID</th><th>Type</th><th>Environnements</th></tr>
    {% for ci in many_envts %}  
       <tr><td>{{ ci.id }}</td><td>{{ci.description.name}}</td><td>{{ci.environments_str}}</td></tr>
    {% endfor %}
</table>
{% endblock content %}

ref/templates/ref/mql_export_sh.html
{% load filter%}{% autoescape off %}{% for compo in instances %}
{% for key,value in compo.items %}MAGE_{{forloop.parentloop.counter}}_{{key | upper}}={{value | ksh_protect_and_quote}}
{% endfor %}MAGE_{{forloop.counter}}_MAGE_FIELDS="{% for key,value in compo.items %}{{key  | upper}}{% if not forloop.last %} {% endif %}{% endfor %}"
{% endfor %}{% endautoescape %}
MAGE_RESULT_COUNT={{ instances | length}}

ref/templates/ref/project_home.html
{% extends "base.html" %}
{% load get_item folder_crumbs from filter %}
{% load cache %}

{% block pagetitle %}Accueil{% endblock %}

{%block navigationButtons%}
    <a href='{% url "admin:index" %}' title="Administration">A</a>
{% endblock %}

{% cache 60 project_home_cache folder_id %}

{% block maintitle %}{{ folder | folder_crumbs }}{% endblock %}

{%block frequentActionsButtons%}
    <a href='{% url "ref:set_acl" folder_id=folder_id %}' title="Editer les habilitations">P</a>
    {%  if folder.empty %}<a href='{% url "ref:folder_delete" folder_id=folder_id %}' title="Supprimer ce dossier">S</a>{%  endif %}
{%  endblock %}

{% block content %}
<div style='color: white;' class='row'>

{%  if folder.subfolders.count > 0 %}
<div class='col-sm-2'>
    <div style='color: white;' class='row'>
		<div class='t2' style='color: black;'>Sous dossiers</div>
	</div>
    <div style='color: white;' class='row'>
        {%  for folder in folder.subfolders.all %}
            <a class='metSquare homeCoulour2' href="{% url 'ref:project_home' folder.id %}">{{folder.name}}<div class='metSquareLong annotation'>{{folder.description}}</div></a>
        {% endfor %}
    </div>
</div>
{%  endif %}

<div class='col-sm-{%  if folder.subfolders.count > 0 %}3{%  else %}5{% endif %}'>
	<div style='color: white;' class='row'>
		<div class='t2' style='color: black;'>Les environnements</div>
	</div>
	<div style='color: white;' class='row'>	
		<a class='metSquare homeCoulour1' href="{% url 'ref:cartoform' folder_id %}">Carte interactive</a>
		<a class='metSquare homeCoulour1' href="{% url 'ref:grscope' folder_id %}">Carte complète du contenu du dossier</a>
		<a class='metSquare homeCoulour1' href="{% url 'ref:new_item' %}">Créer un élément de référentiel</a>
        <a class='metSquare homeCoulour1' href="{% url 'ref:backuped' folder_id %}">Eléments sauvegardés{% if folder.subfolders.count > 0  %} (dont sous dossiers){% endif %}</a>
        <a class='metSquare homeCoulour1' href="{% url 'ref:shared_ci' folder_id %}">Composants mutualisés de ce dossier</a>
        {% if folder.subfolders.count > 0  %}
        <a class='metSquare homeCoulour1' href="{% url 'ref:shared_ci_rec' folder_id %}">Composants mutualisés de ce dossier et sous dossiers</a>
        {%  endif %}
		<div>
		{% for envt in envts %}
		<a class='metSquare' href="{% url 'ref:envt' envt.id %}">{{envt.name}}<div class='metSquareLong annotation'>{{envt.description}}</div></a>	
		{%endfor %}
		</div>
	</div>
</div>

<div class='col-sm-3'>
	<div style='color: white;' class='row'>
		<div class='t2' style='color: black;'>Gestion de configuration</div>
	</div>
	<div style='color: white;' class='row'>	
		<a class='metSquare homeCoulour2' href="{% url 'scm:lc_installs_envts' %}">Synthèse des versions courantes</a>
		<a class='metSquare homeCoulour2' href="{% url 'scm:deliveries' %}">Livraisons disponibles à l'installation</a>
		<a class='metSquare homeCoulour2' href="{% url 'scm:delivery_create' %}">Référencer une livraison</a>
		<a class='metSquare homeCoulour2' href="{% url 'scm:tag_list' %}">Tags</a>
		<a class='metSquare homeCoulour2' href="{% url 'scm:backup_list' %}">Sauvegardes disponibles</a>
		<a class='metSquare homeCoulour2' href="{% url 'scm:lc_list' %}">Versions disponibles</a>
		<div>
		{% for envt in envts %}
			{% if envt.managed %}
				<a class='metSquare' href="{% url 'scm:envtinstallhist' envt.name %}">Historique {{envt.name}}<div class='metSquareLong annotation'>{{latest_setname|get_item:envt.name}}<br/>{{latest_date|get_item:envt.name|date:"d/m H:i"}}</div></a>
			{% endif %}	
		{%endfor %}
		</div>
	</div>
</div>
<div class='col-sm-2'>
	<div style='color: white;' class='row'>
		<div class='t2' style='color: black;'>{{team_links_title}}</div>
	</div>
	<div style='color: white;' class='row'>	
	{% for link in team_links %}
		<a class='metSquare homeCoulour1' href="{{ link.url }}">{{ link.legend|safe }}</a>
	{% endfor %}
	</div>
</div>
<div class='col-sm-2'>
	<div style='color: white;' class='row'>
		<div class='t2' style='color: black;'>Aides scripting</div>
	</div>
	<div style='color: white;' class='row'>	
		<a class='metSquare homeCoulour2' href="{% url 'ref:types' %}">Types de composants installés</a>
		<a class='metSquare homeCoulour2' href="{% url 'ref:mqltester' %}">Requêteur MQL</a>
		<a class='metSquare homeCoulour2' href="{% url 'ref:types_details' %}">Détail des composants installés</a>
		<a class='metSquare homeCoulour2' href="{% url 'ref:urls' %}">API web partielle pour scripts</a>
		<a class='metSquare homeCoulour2' href="{% url 'ref:cartostructure' %}">Graphe des types de composants</a>
	</div>
	<div class='row'>
	{% for envt in templates %}
		<a class='metSquare' href="{% url 'ref:envt' envt.id %}">Template {{envt.name}}<div class='metSquareLong annotation'>{{envt.description}}</div></a>	
	{%endfor %}
	</div>
</div>
</div>
{% endblock content %}
{% endcache %}

ref/templates/ref/view_carto2.html
{% extends "base.html" %}
{% load static %}

{% block pagetitle %}GE{% endblock %}
{% block maintitle %}Carte interactive{% endblock %}
{% block scripts %}
<script type="text/javascript" src='{% static "d3.min.js" %}'></script>
<script type="text/javascript" src='{% static "dagre-d3.min.js" %}'></script>
<script type="text/javascript" src='{% static "jquery-1.11.2.min.js" %}'></script>
<script type="text/javascript">
function refresh_graph()
{
	$.ajax(
	{
		url : '{% url "ref:cartoformdata" project.pk %}',
		type : "POST",
		dataType : "json",
		data: $("#ff").serialize(),
	}).done(function(json)
	{
		digraph = dagreD3.json.decode(json['nodes'], json['edges']);
		
		var renderer = new dagreD3.Renderer();
		$("svg g").empty();
		renderer.run(digraph, d3.select("svg g"));
	});
}

$(document).ready(function()
{
	$('#refresh').on('click', function() { refresh_graph(); });
});
</script>
{% endblock scripts %}

{% block content %}

<div class='container-fluid'>
	<div class='col-md-1 bulletLessList'>
		<button id='refresh'>Refresh</button>
		<form id='ff' method='post'>
            {{ formset }}
		</form>
		
	</div>
	<div class='col-md-11'>
		<svg width=5024 height=5024>
		    <g transform="translate(20,20) scale(0.7)"/>
		</svg>
	</div>	
</div>
{% endblock content %}