MAGE/urls.py
# coding: utf-8
'''
    @license: Apache License, Version 2.0
    @copyright: 2007-2022 Marc-Antoine Gouillart
    @author: Marc-Antoine Gouillart
'''

from django.urls import include, path, re_path
from django.contrib.admin import autodiscover
from django.contrib.auth import views as auth_views
from ref.admin import site
from django.conf import settings
autodiscover()
from ref.views.misc import welcome
from ref import views as ref_views

urlpatterns = [
    # core applications
    re_path(r'^ref/', include('ref.urls')),
    re_path(r'^scm/', include('scm.urls')),

    # Login & co
    re_path(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    re_path(r'^accounts/scriptlogin/(?P<username>.*)/(?P<password>.*)$', ref_views.misc.script_login, name='script_login'),
    re_path(r'^accounts/scriptlogin$', ref_views.misc.script_login_post, name='script_login_post'),
    re_path(r'^accounts/forcelogging$', ref_views.misc.force_login, name='force_login'),
    re_path(r'^accounts/scriptlogout$', ref_views.misc.script_logout, name='script_logout'),
    re_path(r'^accounts/logout/$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    re_path(r'^.*/logout/$', auth_views.LogoutView.as_view(next_page='/')),  # including admin logout
    
    # Admin & admin doc
    re_path(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    re_path(r'^admin/', site.urls),
    
    # Welcome screen (slash mapping)
    re_path(r'^$', welcome, name='welcome'),
]

if settings.DEBUG:
    try:
        import debug_toolbar
        urlpatterns += [ path('__debug__/', include(debug_toolbar.urls)), ]
    except:
        pass

ref/urls.py
# coding: utf-8
'''
    @license: Apache License, Version 2.0
    @copyright: 2007-2022 Marc-Antoine Gouillart
    @author: Marc-Antoine Gouillart
'''

from django.urls import include, path, re_path
from ref import views

app_name='ref'

urlpatterns_project = [
    ###########################################################################
    ## Interactive views
    ###########################################################################

    # Welcome pages
    re_path(r'^$', views.misc.project, name='project'),

    # Environment referential consultation
    re_path(r'^envt/shared/$', views.shared_ci, name='shared_ci'),
    re_path(r'^envt/(?P<envt_id>\d+)$', views.envt, name='envt'),
    re_path(r'^envt/(?P<envt_name>.*)/duplicate$', views.envt_duplicate_name, name='envt_duplicate'),

    # Meta descriptions consultation (modification is inside admin)
    re_path(r'type/$', views.model_types, name='types'),
    re_path(r'types_details/$', views.model_detail, name='types_details'),

    ## CI creation and edit forms
    re_path(r'ci/new/$', views.new_items, name='new_item'),
    re_path(r'ci/new/(?P<description_id>\d*)$', views.new_ci_step1, name='new_item_ci'),
    re_path(r'ci/(?P<instance_id>\d*)$', views.new_ci_step2, name='edit_ci'),
    re_path(r'^instance/envt/(?P<envt_id>\d+)$', views.envt_instances, name='instance_envt'),

    ## Graphs
    re_path(r'gph/full/$', views.carto_full, name='grfull'),
    re_path(r'gph/marsupilamographe/$', views.carto_form, name='cartoform'),
    re_path(r'gph/mplgdata/$', views.carto_content_form, name='cartoformdata'),
    re_path(r'gph/mplgdatafull/(?P<collapse_threshold>\d+)/$', views.carto_content_full, name='cartofulldata'),
    re_path(r'gph/mplgdatasimple/(?P<ci_id_list>[\d,]*)/(?P<collapse_threshold>\d+)/(?P<select_related>\d+)$', views.carto_content, name='cartosimpledata'),
    re_path(r'gph/mplgdatadebug$', views.carto_debug, name='cartodebugdata'),
    re_path(r'gph/structuredata/$', views.carto_description_content, name='cartostructuredata'),
    re_path(r'gph/structure/$', views.carto_description, name='cartostructure'),

    ## Misc
    re_path(r'ci/backuped/$', views.backuped, name='backuped'),

    ## Referential debug/migration
    re_path(r'^debug$', views.debug, name='debug'),
    re_path(r'^instance/debug/all$', views.edit_all_comps_meta, name='instance_all'),
    re_path(r'^instance/debug/descr/(?P<descr_id>\d+)$', views.descr_instances_reinit, name='instance_descr_reinit'),
    re_path(r'^control$', views.control, name='control'),
]

urlpatterns_nonproject = [
    ## Misc (pages)
    re_path(r'urls/$', views.urls, name='urls'),
    re_path(r'clearcache', views.clear_cache, name='clear_cache'),

    ## Script helpers (bash script download)
    re_path(r'^helpers/lib/bash$', views.shelllib_bash, name='helper_bash'),


    ###########################################################################
    ## Script APIs
    ###########################################################################

    ## MQL (scripting API)
    re_path(r'mqltester/$', views.mql_tester, name='mqltester'),
    re_path(r'mql/(?P<output_format>.*)/(?P<query>.*)$', views.mql_query, name='mqlquery'),
]

urlpatterns = [
    re_path(r'^project/(?P<project_id>[\w\-_]+)/', include(urlpatterns_project)),
    path('', include(urlpatterns_nonproject)),
]

scm/urls.py
# coding: utf-8
'''
    @license: Apache License, Version 2.0
    @copyright: 2007-2022 Marc-Antoine Gouillart
    @author: Marc-Antoine Gouillart
'''

from django.urls import re_path, include
from django.conf import settings

from scm import views

app_name='scm'

# Interactive views & forms
urlpatterns_interactive = [
    ###########################################################################
    ## Interactive views
    ###########################################################################

    # Progression
    re_path(r'envt/(?P<envt_name>.+)/hist/(?P<limit>\d+)/', views.all_installs, name='envtinstallhistprm'),
    re_path(r'envt/(?P<envt_name>.+)/hist/', views.all_installs, {'limit': 90}, name='envtinstallhist'),

    # Delivery referential
    re_path(r'delivery/$', views.delivery_list, name='deliveries'),
    re_path(r'delivery/(?P<iset_id>\d+)$', views.delivery, name='delivery_detail'),

    # Delivery hand-off forms
    re_path(r'delivery/edit/$', views.delivery_edit, name='delivery_create'),
    re_path(r'delivery/(?P<iset_id>\d*)/edit/$', views.delivery_edit, name='delivery_edit'),
    re_path(r'delivery/(?P<iset_id>\d*)/editdep/$', views.delivery_edit_dep, name='delivery_edit_dep'),

    # Applying installable sets/items - forms
    re_path(r'is/(?P<iset_id>\d*)/testonenvtform/(?P<envt_id_or_name>.+)$', views.iset_test, name='delivery_prereqs_test'),
    re_path(r'is/(?P<iset_id>\d*)/applytoenvt/(?P<envt_id_or_name>.+)/force$', views.iset_apply_envt, {'force_prereqs' : True}, name='iset_apply_envt_force'),
    re_path(r'is/(?P<iset_id>\d*)/applytoenvt/(?P<envt_id_or_name>.+)$', views.iset_apply_envt, {'force_prereqs' : False}, name='iset_apply_envt_force'),
    re_path(r'bck/$', views.backup_list, name='backup_list'),
    re_path(r'bck/archive$', views.backup_list, {'archive': True}, name='backup_list_archive'),
    re_path(r'bck/(?P<bck_id>\d*)$', views.backup_detail, name='backup_detail'),
    
    # Backup
    re_path(r'bck/create/envtdefault/(?P<envt_name>.*)$', views.backup_envt, name='backup_envt'),
    re_path(r'bck/create/form/(?P<envt_name>.*)$', views.backup_envt_manual, name='backup_envt_manual'),
    re_path(r'bck/latest/ci/(?P<ci_id>\d*)/age$', views.latest_ci_backupset_age_mn, name='latest_ci_backupset_age_mn'),
    re_path(r'bck/latest/ci/(?P<ci_id>\d*)/id$', views.latest_ci_backupset_id, name='latest_ci_backupset_id'),

    # Retrieving current version of elements
    re_path(r'version/summary/$', views.lc_versions_per_environment, name='lc_installs_envts'),
    re_path(r'version/lc/$', views.lc_list, name='lc_list'),
    re_path(r'version/lc/(?P<lc_id>\d*)$', views.lc_versions, name='lc_versions'),

    # Tags
    re_path(r'tag/$', views.tag_list, name='tag_list'),
    re_path(r'tag/(?P<tag_id>\d*)$', views.tag_detail, name='tag_detail'),
    re_path(r'tag/create/(?P<envt_name>.*)/(?P<tag_name>.*)$', views.tag_create, name='tag_create'),
    re_path(r'tag/(?P<tag_id>.*)/remove$', views.tag_remove, name='tag_remove'),

    # IS life cycle
    re_path(r'is/(?P<iset_id>\d*)/validate$', views.iset_validate, name='iset_validate'),
    re_path(r'is/(?P<iset_id>\d*)/invalidate$', views.iset_invalidate, name='iset_invalidate'),
    re_path(r'is/(?P<is_id>\d*)/archive$', views.iset_archive, name='iset_archive'),
    re_path(r'is/(?P<is_id>\d*)/unarchive$', views.iset_unarchive, name='iset_unarchive'),
]

urlpatterns_script = [

    ###########################################################################
    ## Script APIs (using direct path without project for ascending compatibility)
    ###########################################################################

    # Applying installable sets/items
    re_path(r'is/(?P<iset_id>\d*)/testonenvtscript/(?P<envt_id_or_name>.+)$', views.iset_test_script, name='delivery_prereqs_test_script'),
    re_path(r'is/(?P<iset_id>\d*)/applytoenvt/(?P<envt_id_or_name>.+)$', views.iset_apply_envt, name='iset_apply_envt'),
    re_path(r'ii/(?P<ii_id>\d+)/apply/(?P<envt_name>.+)/(?P<instance_id>\d+)$', views.delivery_ii_apply_envt, name='delivery_apply_ii_single'),
    re_path(r'ii/(?P<ii_id>\d+)/testonenvtscriptfull/(?P<envt_name>.+)$', views.delivery_ii_test_envt, {'full_delivery': True}, name='delivery_test_ii_set'),
    re_path(r'ii/(?P<ii_id>\d+)/testonenvtscriptsingle/(?P<envt_name>.+)$', views.delivery_ii_test_envt, name='delivery_test_ii_single'),
    re_path(r'ii/(?P<ii_id>\d+)/installmethod/(?P<ci_id>\d+)$', views.ii_test_applicable_to_ci, name='ii_test_compat_ci'),

    # Retrieving current version of elements
    re_path(r'version/lc/(?P<lc_id>\d*)/json$', views.get_lc_versions, name='lc_versions_export'),
    
    # Tags
    re_path(r'tag/create/(?P<envt_name>.*)/(?P<tag_name>.*)$', views.tag_create_script, name='tag_script_create'),
    re_path(r'tag/(?P<tag_id>.*)/remove$', views.tag_remove_script, name='tag_script_remove'),
    
    # Backup
    re_path(r'bck/create/envtdefault/(?P<envt_name>.*)$', views.backup_envt, name='backup_script_envt'),
    re_path(r'bck/create/script/(?P<envt_name>.*)/(?P<ci_id>\d*)$', views.backup_script, name='backup_script_create'),
    re_path(r'bck/create/script/(?P<envt_name>.*)/(?P<ci_id>\d*)/(?P<bck_id>\d*)$', views.backup_script, name='backup_script_add'),
    re_path(r'bck/latest/envt/(?P<envt_name>.*)/id$', views.latest_envt_backupset_id, name='latest_envt_backupset_id'),

    # Queries on IS & II
    re_path(r'is/(?P<iset>.*)/export/(?P<output_format>.*)$', views.iset_export, name='iset_export'),
    re_path(r'is/(?P<iset_name>.*)/id$', views.iset_id, name='iset_id'),
    re_path(r'is/(?P<iset_id>.+)/ii/iicompatlist/(?P<ci_id>\d+)$', views.iset_get_applicable_ii, name='iset_ii_ii_compat'),
    re_path(r'ii/(?P<ii_id>\d+)/export/sh$', views.ii_export, name='ii_export'),

    # IS life cycle
    re_path(r'is/(?P<iset_id>\d*)/validate$', views.iset_validate_script, name='iset_script_validate'),
    re_path(r'is/(?P<iset_id>\d*)/invalidate$', views.iset_invalidate_script, name='iset_script_invalidate'),
    re_path(r'is/(?P<is_id>\d*)/archive$', views.iset_archive_script, name='iset_script_archive'),
    re_path(r'is/(?P<is_id>\d*)/unarchive$', views.iset_unarchive_script, name='iset_script_unarchive'),
]

urlpatterns = [
    re_path(r'^project/(?P<project_id>[\w\-_]+)/', include(urlpatterns_script)),
    re_path(r'^', include((urlpatterns_script, 'scm'), namespace='default_project'), kwargs={'project_id': settings.DEFAULT_PROJECT_ID}),
    re_path(r'^project/(?P<project_id>[\w\-_]+)/', include(urlpatterns_interactive)),
]

scm/views/backup.py
# coding: utf-8

## Python imports

## Django imports
from django import forms
from django.contrib.auth.decorators import permission_required
from django.utils.timezone import now
from django.shortcuts import render, redirect
from django.http.response import HttpResponse, HttpResponseBadRequest
from ref.permissions.perm_check import permission_required_project_aware

## MAGE imports
from scm.backup import register_backup_envt_default_plan, register_backup
from scm.models import BackupSet, Environment, ComponentInstance
from django.db.models.aggregates import Count


def backup_list(request, archive=False):
    return render(request, 'scm/backup_list.html', {'backups': BackupSet.objects.filter(removed__isnull=not archive, project=request.project).annotate(item_count = Count('all_items')).order_by('from_envt', 'set_date').\
                                                    select_related('from_envt'), 'archive' : archive})

def backup_detail(request, bck_id):
    return render(request, 'scm/backup_detail.html', {'bck': BackupSet.objects.get(pk=bck_id, project=request.project)})

@permission_required_project_aware('ref.modify_project')
@permission_required('scm.add_backupset')
def backup_envt(request, envt_name):
    b = register_backup_envt_default_plan(envt_name, now())
    return redirect('scm:backup_detail', bck_id=b.id, project=request.project)

@permission_required_project_aware('ref.modify_project')
@permission_required('scm.add_backupset')
def backup_envt_script(request, envt_name):
    b = register_backup_envt_default_plan(envt_name, now())
    return HttpResponse(b.id, content_type='text/plain')

@permission_required_project_aware('ref.modify_project')
@permission_required('scm.add_backupset')
def backup_envt_manual(request, envt_name):
    e = Environment.objects.get(name=envt_name)

    if request.method == 'POST':  # If the form has been submitted...
        f = BackupForm(request.POST, envt=e)

        if f.is_valid():
            instances = ComponentInstance.objects.filter(pk__in=f.cleaned_data['instances'])
            bs = register_backup(e, f.cleaned_data['date'], "MANUAL - %s" % f.cleaned_data['description'], *instances)
            return redirect('scm:backup_detail', bck_id=bs.id)
    else:
        f = BackupForm(envt=e)

    return render(request, 'scm/backup_create_manual.html', {'form': f, 'envt': e})

@permission_required_project_aware('ref.modify_project')
@permission_required('scm.add_backupset')
def backup_script(request, envt_name, ci_id, bck_id=None):
    try:
        bs = register_backup(envt_name, now(), bck_id, ComponentInstance.objects.get(pk=ci_id), description='script backup')
        return HttpResponse(bs.id, content_type='text/plain')
    except Exception as e:
        return HttpResponseBadRequest(e, content_type='text/plain')


def latest_ci_backupset_age_mn(request, ci_id):
    response = HttpResponse(content_type='text/plain')
    try:
        ci = ComponentInstance.objects.get(pk=ci_id)
        bis = BackupSet.objects.filter(all_items__instance__id=ci.id)
        if bis.count() == 0:
            response.write("-1")
        else:
            bis = bis.latest('set_date')
            response.write(int(round((now() - bis.set_date).total_seconds() / 60, 0)))
    except (ComponentInstance.DoesNotExist, BackupSet.DoesNotExist):
        response.write("-1")
    return response

def latest_ci_backupset_id(request, ci_id):
    response = HttpResponse(content_type='text/plain')
    try:
        bis = BackupSet.objects.filter(all_items__instance__id=ci_id)
        if bis.count() == 0:
            response.write("-1")
        else:
            response.write(bis.latest('set_date').pk)
    except (ComponentInstance.DoesNotExist, BackupSet.DoesNotExist):
        response.write("-1")
    return response

def latest_envt_backupset_id(request, envt_name):
    response = HttpResponse(content_type='text/plain')
    try:
        bis = BackupSet.objects.filter(from_envt__name=envt_name)
        if bis.count() == 0:
            response.write("-1")
        else:
            response.write(bis.latest('set_date').pk)
    except (ComponentInstance.DoesNotExist, BackupSet.DoesNotExist):
        response.write("-1")
    return response


class BackupForm(forms.Form):
    description = forms.CharField(max_length=90, required=False)
    date = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M', ])
    instances = forms.TypedMultipleChoiceField(choices=(), widget=forms.widgets.CheckboxSelectMultiple, coerce=int)

    def __init__(self, *args, **kwargs):
        self.envt = kwargs['envt']
        del kwargs['envt']
        super(BackupForm, self).__init__(*args, **kwargs)
        self.fields['instances'].choices = [(i.pk, i.__str__()) for i in self.envt.component_instances.all()]

scm/views/logicalcomponent.py
# coding: utf-8
""" Logical component model """

## Python imports
import json

## Django imports
from django.views.decorators.cache import cache_control
from django.shortcuts import render
from django.http.response import HttpResponse

## MAGE imports
from ref.models import LogicalComponent
from django.db.models.query import Prefetch
from scm.models import LogicalComponentVersion, InstallableSet, InstallableItem


def get_lc_versions(request, lc_id):
    lc = LogicalComponent.objects.get(pk=lc_id, application__project=request.project)
    res = []
    for v in lc.versions.all().order_by('pk'):
        res.append((v.id, v.version))

    return HttpResponse(json.dumps(res))

def lc_list(request):
    lcs = LogicalComponent.objects.filter(active=True, scm_trackable=True, application__project=request.project).order_by('application', 'name').select_related('application')
    return render(request, 'scm/lc_versions.html', {'lcs': lcs})

@cache_control(must_revalidate=True)
def lc_versions(request, lc_id):
    lc = LogicalComponent.objects.filter(application__project=request.project).select_related('application').prefetch_related(
               Prefetch('versions', queryset=LogicalComponentVersion.objects.prefetch_related(Prefetch('installed_by', queryset=InstallableItem.objects.all().select_related('belongs_to_set__backupset'))))
           ).get(pk=lc_id)
    return render(request, 'scm/lc_versions_detail.html', {'lc': lc})

scm/templates/scm/backup_detail.html
{% extends "base.html" %}
{% block pagetitle %}Gestion de configuration{% endblock %}
{% block maintitle %}Backup {{bck.name}}{% endblock %}

{%block frequentActionsButtons%}
{% if not bck.removed %}
<a href="{% url 'scm:iset_archive' project.pk bck.id %}" title="Archiver (marquer comme non disponible)">A</a>
{% else %}
<a href="{% url 'scm:iset_unarchive' project.pk bck.id %}" title="Sortir de l'archive (marquer comme disponible)">U</a>
{% endif %}
<a href="{% url 'scm:delivery_detail' project.pk bck.id %}" title="Voir comme une livraison">L</a>
{% endblock %}

{%block navigationButtons%}
<a href="{% url 'scm:backup_list' project.pk %}" title="Liste des sauvegardes">↑</a>
{%endblock%}

{% block content %}

<div class='metContainer metSection metDefaultBackground'>
	<table>
		<tr><td>Environnement source</td><td>{{bck.from_envt}}</td></tr>
		<tr><td>Pris le</td><td>{{bck.set_date}}</td></tr>
	</table>
</div>

<div class='t2'>Contenu</div>
{% for item in bck.all_items.all %}
	<div class='metContainer metRectList metDefaultBackground'>
		{{item.instance.name}}
		{% if item.instance_configuration %} - {{ item.instance_configuration.result_of.what_is_installed.version }} {% else %} - no version {% endif %}
		<div class='annotation'>{{ item.instance.instanciates }}</div>
	</div>
{% endfor %}

{% endblock content %}

scm/templates/scm/delivery_detail.html
{% extends "base.html" %}
{% block pagetitle %}Gestion de configuration{% endblock %}
{% block maintitle %}Livraison {{delivery.name}}{% endblock %}

{%block frequentActionsButtons%}
<a href="{% url 'scm:delivery_edit' project.pk delivery.id %}" title="Editer la liraison">E</a>
<a href="{% url 'scm:delivery_edit_dep' project.pk delivery.id %}" title="Editer les dépendances">D</a>
{% if delivery.status > 1 %}
	<a href="{% url 'scm:iset_validate' project.pk delivery.id %}" title="Valider la livraison">V</a>
{% else %}
    <a href="{% url 'scm:iset_invalidate' project.pk delivery.id %}" title="Invalider la livraison">U</a>
{% endif %}

<a href='{% url "scm:iset_export" project.pk delivery.id "csvc" %}' title="CSV du contenu">C</a>
<a href='{% url "scm:iset_export" project.pk delivery.id "sh" %}' title="Script shell détaillant le contenu">S</a>
{%endblock%}

{%block navigationButtons%}<a href="{% url 'scm:deliveries' project.pk %}" title="Liste des livraisons">↑</a>{%endblock%}

{% block content %}

<div class='metContainer metSection metDefaultBackground'>
	<table>
		<tr><td>Enregistrée le</td><td> : {{ delivery.set_date|date:"d/m/Y" }}</td></tr>
		<tr><td>Description courte</td><td> : {{delivery.description}}</td>	</tr>
		<tr><td>Tickets corrigés</td><td> : {{delivery.tickets}}</td></tr>
		<tr><td>Disponible</td><td> : {{delivery.available}}</td></tr>
		<tr><td>Statut</td><td> : {{delivery.get_status_display}}</td></tr>
		{% if perms.scm.download_ii and delivery.datafile %}
		<tr><td>Fichier de données</td><td> : <a href='{{delivery.datafile.url}}'>Télécharger</a></td></tr>
		{% endif %}
	</table>
</div>

{% for ii in delivery.set_content.all %}
	<div class='metContainer metFreeRect metDefaultBackground'>
		{% if perms.scm.download_ii and ii.datafile %}
		<a class='t3' href='{{ii.datafile.url}}'>[{{ii.what_is_installed.logical_component.application}} {{ ii.what_is_installed.logical_component.name }}] version [{{ ii.what_is_installed.version }}]</a><br/>
		{% else %}
		<div class='t3'>[{{ii.what_is_installed.logical_component.application}} {{ ii.what_is_installed.logical_component.name }}] version [{{ ii.what_is_installed.version }}]</div>
		{% endif %}

		<div class='metContainer smallContent'>
			{% for dep in ii.dependencies.all %}
				<div>Requiert version [{{dep.depends_on_version.logical_component.application}} {{dep.depends_on_version.logical_component.name}}] {{dep.operator}} [{{dep.depends_on_version.version}}]</div>
			{%endfor%}
		</div>
		
		{% for method in ii.how_to_install.all %}
			<div class='metContainer metFreeRect'>
				<div class='smallContent'>S'installe avec [{{ method.name }}]</div>
				{%comment%}{% for cic in method.method_compatible_with.all %}
					{% if cic.implements_id == ii.what_is_installed.logical_component_id %}
						<div class='smallContent'>Compatible avec {{ cic.name }} (via {{ method.name }})</div>
					{%endif%}
				{% endfor %}{% endcomment %}
			</div>
		{% endfor %} 
	</div>
{% endfor %}

<br/>
{% if delivery.available %}
	{% for envt in envts %}
		<a class='metRectList defaultHighlightBackground' href="{% url 'scm:delivery_prereqs_test' project.pk delivery.id envt.id %}">Peut-elle être installée sur {{envt.name}} ?</a>
	{% endfor %}
{% else %}
	<div class='metRectList metErrorBackground'>Livraison non disponible - non installable</div>
{% endif %}
<br/><br/>
<table class='table table-condensed table-bordered table-hover'>
    <thead>
        <tr>
            <th>Environnement</th>
            <th>Dernière installation d'un élément de cette livraison</th>
        </tr>        
    </thead>
    <tbody>
        {% for e in envts %}
            <tr>
                <td><a href="{% url 'scm:envtinstallhist' envt_name=e.name project_id=project.pk %}">{{e.name}}</a></td>
                <td>
                {% for ee in installs %}
                    {% if ee.id == e.id %}{{ee.dd}}{%endif%}
                {% endfor %}
                </td>
            </tr>
        {%endfor%}
    </tbody>
</table>

{% endblock content %}

scm/templates/scm/envt_all_installs.html
{% extends "base.html" %}
{% block pagetitle %}Gestion de configuration{% endblock %}
{% block maintitle %}Installations sur {{envt.name}} ces {{limit}} derniers jours{% endblock %}

{%block frequentActionsButtons%}
<a href="{% url 'scm:tag_create' project.pk envt.name envt.potential_tag %}" title="Créer un tag">T</a>
<a href="{% url 'scm:backup_envt' project.pk envt.name %}" title="Enregistrer manuellement un backup par défaut">B</a>
<a href="{% url 'scm:backup_envt_manual' project.pk envt.name %}" title="Enregistrer manuellement un backup de certains éléments">M</a>
{%endblock%}

{% block content %}

<table class='visibleTable'>
	<thead>
		<tr>
			<td></td>
			<td style='width: 7em;'>Date</td>
			{% for lc in logical_components %}
				<td>{{lc.application}} {{lc.name}}</td>
			{% endfor %}			
		</tr>
		
	</thead>
	
	<tbody>
	
		<tr style='background-color: #D6D6D6; font-style: italic;'>
			<td>Version actuelle</td>
			<td></td>
			{% for lc in logical_components %}
                <td>
				{% for key, value in versions.items %}
					{% ifequal key.id lc.id %}
						{% for v in value %}{{v}} {% endfor %}
					{% endifequal %}
				{% endfor %}
                </td>
			{% endfor %}	
		</tr>
		{% for install in installs %}
			<tr>
				<td>
					<div class='metContainer' style='background:#D6D6D6;margin:0;' >
						<a href="{% url "scm:delivery_detail" project_id=project.pk iset_id=install.installed_set.pk %}"> {{ install.installed_set.name }}</a>
					</div>
				</td>
				<td>
					<div>{{ install.install_date|date:"d/m H:i" }}</div>
				</td>
				{% for lc in logical_components %}
					<td style='height:100%;'>
					{% for cic in install.modified_components.all %}
						{% ifequal cic.component_instance.instanciates.implements_id lc.id %}
							<div class='metContainer' style='background-color: #4D944D;'> {{ cic.result_of.what_is_installed.version }}</div>
						{% endifequal %}
					{% endfor %}
					</td>
				{% endfor %}
			</tr>
		{% endfor %}
	</tbody>
</table>

{% endblock content %}

scm/templates/scm/tag_list.html
{% extends "base.html" %}
{% block pagetitle %}Gestion de configuration{% endblock %}
{% block maintitle %}Liste des tags{% endblock %}

{% block content %}

{% regroup tags by from_envt as envt_list %}


{% for envt in envt_list %}
<div class='row'>
	<div class='col-md-1'>
		<div class='metRectFixedwidth metLineHeader'>{{envt.grouper.name}}</div>
	</div>
	<div class='col-md-11'>
		{% for tag in envt.list %}
		<a class='metContainer metRectList defaultHighlightBackground' href="{% url 'scm:tag_detail' project.pk tag.id %}">
			{{tag.name}}
		</a>
		{% endfor %}
	</div>
</div>
{% endfor %}

{% endblock content %}