MAGE/urls.py
# coding: utf-8
'''
    @license: Apache License, Version 2.0
    @copyright: 2007-2022 Marc-Antoine Gouillart
    @author: Marc-Antoine Gouillart
'''

from django.urls import include, path, re_path
from django.contrib.admin import autodiscover
from django.contrib.auth import views as auth_views
from ref.admin import site
from django.conf import settings
autodiscover()
from ref.views.misc import welcome
from ref import views as ref_views

urlpatterns = [
    # core applications
    re_path(r'^ref/', include('ref.urls')),
    re_path(r'^scm/', include('scm.urls')),

    # Login & co
    re_path(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    re_path(r'^accounts/scriptlogin/(?P<username>.*)/(?P<password>.*)$', ref_views.misc.script_login, name='script_login'),
    re_path(r'^accounts/scriptlogin$', ref_views.misc.script_login_post, name='script_login_post'),
    re_path(r'^accounts/forcelogging$', ref_views.misc.force_login, name='force_login'),
    re_path(r'^accounts/scriptlogout$', ref_views.misc.script_logout, name='script_logout'),
    re_path(r'^accounts/logout/$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    re_path(r'^.*/logout/$', auth_views.LogoutView.as_view(next_page='/')),  # including admin logout
    
    # Admin & admin doc
    re_path(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    re_path(r'^admin/', site.urls),
    
    # Welcome screen (slash mapping)
    re_path(r'^$', welcome, name='welcome'),
]

if settings.DEBUG:
    try:
        import debug_toolbar
        urlpatterns += [ path('__debug__/', include(debug_toolbar.urls)), ]
    except:
        pass

ref/urls.py
# coding: utf-8
'''
    @license: Apache License, Version 2.0
    @copyright: 2007-2022 Marc-Antoine Gouillart
    @author: Marc-Antoine Gouillart
'''

from django.urls import include, path, re_path
from ref import views

app_name='ref'

urlpatterns_project = [
    ###########################################################################
    ## Interactive views
    ###########################################################################

    # Welcome pages
    re_path(r'^$', views.misc.project, name='project'),

    # Environment referential consultation
    re_path(r'^envt/shared/$', views.shared_ci, name='shared_ci'),
    re_path(r'^envt/(?P<envt_id>\d+)$', views.envt, name='envt'),
    re_path(r'^envt/(?P<envt_name>.*)/duplicate$', views.envt_duplicate_name, name='envt_duplicate'),

    # Meta descriptions consultation (modification is inside admin)
    re_path(r'type/$', views.model_types, name='types'),
    re_path(r'types_details/$', views.model_detail, name='types_details'),

    ## CI creation and edit forms
    re_path(r'ci/new/$', views.new_items, name='new_item'),
    re_path(r'ci/new/(?P<description_id>\d*)$', views.new_ci_step1, name='new_item_ci'),
    re_path(r'ci/(?P<instance_id>\d*)$', views.new_ci_step2, name='edit_ci'),
    re_path(r'^instance/envt/(?P<envt_id>\d+)$', views.envt_instances, name='instance_envt'),

    ## Graphs
    re_path(r'gph/full/$', views.carto_full, name='grfull'),
    re_path(r'gph/marsupilamographe/$', views.carto_form, name='cartoform'),
    re_path(r'gph/mplgdata/$', views.carto_content_form, name='cartoformdata'),
    re_path(r'gph/mplgdatafull/(?P<collapse_threshold>\d+)/$', views.carto_content_full, name='cartofulldata'),
    re_path(r'gph/mplgdatasimple/(?P<ci_id_list>[\d,]*)/(?P<collapse_threshold>\d+)/(?P<select_related>\d+)$', views.carto_content, name='cartosimpledata'),
    re_path(r'gph/mplgdatadebug$', views.carto_debug, name='cartodebugdata'),
    re_path(r'gph/structuredata/$', views.carto_description_content, name='cartostructuredata'),
    re_path(r'gph/structure/$', views.carto_description, name='cartostructure'),

    ## Misc
    re_path(r'ci/backuped/$', views.backuped, name='backuped'),

    ## Referential debug/migration
    re_path(r'^debug$', views.debug, name='debug'),
    re_path(r'^instance/debug/all$', views.edit_all_comps_meta, name='instance_all'),
    re_path(r'^instance/debug/descr/(?P<descr_id>\d+)$', views.descr_instances_reinit, name='instance_descr_reinit'),
    re_path(r'^control$', views.control, name='control'),
]

urlpatterns_nonproject = [
    ## Misc (pages)
    re_path(r'urls/$', views.urls, name='urls'),
    re_path(r'clearcache', views.clear_cache, name='clear_cache'),

    ## Script helpers (bash script download)
    re_path(r'^helpers/lib/bash$', views.shelllib_bash, name='helper_bash'),


    ###########################################################################
    ## Script APIs
    ###########################################################################

    ## MQL (scripting API)
    re_path(r'mqltester/$', views.mql_tester, name='mqltester'),
    re_path(r'mql/(?P<output_format>.*)/(?P<query>.*)$', views.mql_query, name='mqlquery'),
]

urlpatterns = [
    re_path(r'^project/(?P<project_id>[\w\-_]+)/', include(urlpatterns_project)),
    path('', include(urlpatterns_nonproject)),
]

MAGE/templates/base.html
{% load static %}<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<link rel="shortcut icon" href='{% static "fav.png" %}' />
		
		<title>{%block pagetitle%}MAGE{%endblock pagetitle%}</title>
		{%block scripts%}{%endblock%}
		{%block other_css%}{%endblock%}
		
		<link media="all" type="text/css" href="{% static "bootstrap-3.3.4/css/bootstrap.min.css" %}" rel="stylesheet"/>
		<link media="all" type="text/css" href="{% static "mage.css" %}" rel="stylesheet"/>
		
		<script type="text/javascript">function back() 
		{
			if (document.referrer !== null && document.referrer !== "")
			{
				if (document.referrer.indexOf("accounts/login") === -1)
				{
					history.back();return false;
				}
				else
				{
					history.go(-2);return false;
				}
			}
			else
			{
				window.location = '/';
				return false;
			}
		}</script>
	</head>
	<body>
		<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class='container-fluid'>
				<div class='navbar-header'>
                    <a class="navbar-brand" href="{% url 'welcome' %}">MAGE</a>
				</div>
                
                <div class="collapse navbar-collapse">
                    {%  if project %}
                        <ul class="nav navbar-left navbar-project">
                            <li>
                                <p class="navbar-text caps">
                                    <a class="nav-link nav-link-project" href="{% url 'ref:project' project.pk %}">{{ project.name }}</a>
                                </p>
                            </li>
                        </ul>
                    {% endif %}

                    <ul class="nav navbar-left">
                        <li><p class="navbar-text caps pageTitle">{%block maintitle%}{%endblock%}</p></li>
                    </ul>               
                
                    <ul class="nav navbar-nav navbar-right" id='inout'>
                        {% if user.is_authenticated %}
                        <li>
							{% if user.last_name and user.first_name %}
							<p class="navbar-text">{{ user.first_name }} {{ user.last_name }}</p>
							{% else %}
							<p class="navbar-text">{{ user.username }}</p>
							{% endif %}
                        </li>
                        {% endif %}
                        <li>
                            {% if user.is_authenticated %}<a href="{% url 'logout' %}">Se déconnecter</a>
                            {% else %}<a href="{% url 'force_login' %}?next={{request.path}}">S'authentifier</a>{% endif %}
                        </li>
                        <li id='quickAccessButtons'>
                            <span id='quickAccessActionButtons'>{%block frequentActionsButtons%}{%endblock%}</span>
                            <span id='quickAccessNavigationButtons'>
                                {%block navigationButtons%}{%endblock%}
                            </span>
                        </li>
                    </ul>	
                </div>			
			</div>
		</div>
		{% if messages %}
		<div class='bloc1'>
		    {% for message in messages %}
		    <li>{{ message }}</li>
		    {% endfor %}
		</div>
		{% endif %}
		<div class='container-fluid'>{%block content%}{%endblock content%}</div>		
	</body>
</html>

MAGE/templates/fed_login.html
{% extends "base.html" %}

{% block pagetitle %}Authentification{% endblock pagetitle %}


{% block content %}

    <div class='metRibbonSplash metContainer'>
        <div class='metRibbonSplashContent'>
            <div style='display: inline-block;'>
                <div class='t2'>Accès à une ressource protégée</div>
                {% if user.is_authenticated %}
                    <div>
                        Vous êtes authentifié en tant que "{{ user.username }}" mais ce compte n'a pas les droits
                        nécessaires pour accéder à la ressource demandée.<br/>
                        Veuillez utiliser un compte autorisé à réaliser l'opération, ou revenez à la page précédente.
                    </div>
                {% else %}
                    <div>La ressource ne peut être utilisée par un utilisateur anonyme - veuillez vous identifier.</div>
                {% endif %}

                <div class='metContainer'>
                    <div class="t4">Login applicatif</div>
                    <form method="post" action="{% url 'login' %}">
                        {% csrf_token %}
                        {{ ilform }}
                        <input name="internal_login" type="submit">
                        <input type="hidden" name="next" value="{{ next }}" />
                        {% if form.errors %}
                            <span class='errorlist'>Your username and password didn't match. Please try again.</span>
                        {% endif %}
                    </form>
                </div>

                {% if op_list %}
                    <div class="metContainer">
                        <div class="t4">Login à l'aide d'un des systèmes suivants</div>
                        {% for op_name in op_list %}
                            <a href="{% url 'openid_with_op_name' op_name=op_name %}">{{ op_name }}</a>&nbsp;
                        {% endfor %}
                    </div>
                {% endif %}

                {% if dynamic %}
                    <div class="metContainer">
                        <div class="t4">Login à l'aide d'un fournisseur OpenID Connect provider de votre choix</div>
                        <form method="post">
                            {% csrf_token %}
                            {{ form }}
                            <input type="submit">
                        </form>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

MAGE/templates/login.html
{% extends "base.html" %}

{%block pagetitle%}Authentification{%endblock pagetitle%}


{% block content %}

<div class='metRibbonSplash metContainer'>
	<div class='metRibbonSplashContent'>
		<div style='display: inline-block;'>
			<div class='t2'>Accès à une ressource protégée</div>		
			{% if user.is_authenticated %}
			    <div>
			    	Vous êtes authentifié en tant que "{{ user.username }}" mais ce compte n'a pas les droits nécessaires pour accéder à la ressource demandée.<br/>
			    	Veuillez utiliser un compte autorisé à réaliser l'opération, ou revenez à la page précédente.
			     </div> 
			{% else %}
				<div>La ressource ne peut être utilisée par un utilisateur anonyme - veuillez vous identifier.</div>
			{% endif %}
			<form method="post" action="{% url 'login' %}">
				<table>
					<tr>
						<td>Nom d'utilisateur</td>
						<td>{{ form.username }}</td>
					</tr>
					<tr>
						<td>{{ form.password.label_tag | safe }}</td>
						<td>{{ form.password }}</td>
					</tr>
				</table>
				
				<div class='right'>
					<input type="submit" value="login" />
					<button class='cancel' onclick="back();return false;">cancel</button>
					<input type="hidden" name="next" value="{{ next }}" />
				</div>
				
				{% if form.errors %}
					<span class='errorlist'>Your username and password didn't match. Please try again.</span>
				{% endif %}
			</form>
		</div>
	</div>
</div>

{% endblock %}